apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-ji1i
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-ji1i
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-ji1i
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-ji1i
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-ji1i
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-deploy-tenant/appstudio/dc-metro-map-ji1i@sha256:4af40acc77cd38032787c99efd85dfa218bbd9236a0b082348e5402d3588d8a0
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
